### ISSUE TITLE
Telegram message

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/dmp#106]
Roth provided the text below which should be used for content for the Telegram message that is sent when a form is submitted. # represents a dynamic data field

> Initial data
> #Province name
> #District name
> #Commune name
> - #Hazard type
> - #Disaster date (15 April 2023)
> - #Reported date (16 April 2023)
> - #People affected
> - #Number of deaths
> - #number of injured
> - #Number of houses affected
> - DCDM had submitted the data in the system
> - Please checks and approve, thanks!

**Comment by ericboucher** [comment]
@wadhwamatic can the message be in English? It's tricky to duplicate translation between the frontend and the backend. If English is fine for now it will make this task easier.

**Comment by ericboucher** [comment]
@wadhwamatic `#Number of houses affected ….` do the `...` mean that we have to list all the non-null numbers?

**Comment by wadhwamatic** [comment]
> @wadhwamatic can the message be in English? It's tricky to duplicate translation between the frontend and the backend. If English is fine for now it will make this task easier.

@ericboucher - we can start with English for testing but will need to change everything to Khmer later

**Comment by wadhwamatic** [comment]
> @wadhwamatic `#Number of houses affected ….` do the `...` mean that we have to list all the non-null numbers?

@ericboucher - sorry - you can ignore the '...', that was just copy / paste remnants from Roth's message. We just need a single value here, same as the others

**Comment by ericboucher** [comment]
@wadhwamatic this is where I'm at at the moment:

New initial data reported _AW - test drought report_
Kampong Chhnang
Kampong Tralach
Chres

__Drought__
Disaster date: 2023-05-19
Reported date: 2023-05-19

Affected: 4
Dead: 0
Injured: 0
Houses 0

DCDM has submitted new data in the system. Please check and approved. Thanks!
[Link to form](https://dmp.ovio.org/form/DROUGHT/428293436)
