### ISSUE TITLE
Allow selection of multiple 'other incidents' in the report feature

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/dmp#122]
Users need to select multiple types of 'other incidents'. According to Roth, there are a few incidents which are routinely monitored, so users need the ability to specifically choose which incidents should be included in the report. 

Note: 'other incidents' refers to the form used to collect data on disasters besides drought and floods.

The old version used checkboxes instead of radio buttons to do this on the 'Selective Report' page.
<img width="1129" alt="Screenshot 2023-05-23 at 21 28 48" src="https://github.com/WFP-VAM/dmp/assets/3343536/44ffec84-251e-4878-abfa-8b5535afa881">

**Comment by ericboucher** [comment]
Done in #126
