### ISSUE TITLE
Add a home button

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/dmp#66]
Once you're on a tab, it's not obvious that you can click the logo to go back to the home page.
Maybe we could add a home button, or some other name? @wadhwamatic wdyt?

<img width="1427" alt="Screenshot 2023-04-21 at 4 25 18 PM" src="https://user-images.githubusercontent.com/16843267/233661227-f3f49bfd-3094-422f-9642-2a6f924d8865.png">

**Comment by wadhwamatic** [comment]
Yeah, agreed, a home button is needed
