### ISSUE TITLE
Make links shareable

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/dmp#84]
As a user, I would like to share a direct link to a form, eg. https://wfp-dmp-83.surge.sh/form/FLOOD/420211636

**Comment by ericboucher** [comment]
This does not work on surge but it works on deployed staging and prod domains so I think we're good for now.

See https://surge.sh/help/adding-a-200-page-for-client-side-routing for a way to fix surge deploys. Maybe?

**Comment by ericboucher** [comment]
Note - now that we deploy the app as a static website through amplify, this issue also exists there

**Comment by ericboucher** [comment]
I think that I fixed this by adding this rewrite rule to amplify:

<img width="1402" alt="Screenshot 2023-05-24 at 7 24 59 PM" src="https://github.com/WFP-VAM/dmp/assets/16843267/865b7f5b-bf9f-4391-9ab4-8de97172dd84">

**Comment by ericboucher** [comment]
@sifelix I added the rule above to prod, could you add it to staging? Are there other links we should create redirects for?

**Comment by sifelix** [comment]
Staging updated! It is working well. 
No I don't think so

**Comment by ericboucher** [comment]
I added a note in the deployment Notion doc.
