### ISSUE TITLE
Form data is not aggregating correctly in reports

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/dmp#94]
After making a few edits to two forms I tested today on staging, the results were not aggregating properly. Both reports are for the same day and location, and both are in 'approved' status.

Form 1:
<img width="1850" alt="Screenshot 2023-05-11 at 18 08 38" src="https://github.com/WFP-VAM/dmp/assets/3343536/fef9839f-ad38-4650-be90-ad6ea2422bdb">

Form 2:
<img width="1849" alt="Screenshot 2023-05-11 at 18 08 30" src="https://github.com/WFP-VAM/dmp/assets/3343536/2d38f958-19de-4c05-9480-4656a71435f7">

Report:
<img width="1844" alt="Screenshot 2023-05-11 at 18 26 21" src="https://github.com/WFP-VAM/dmp/assets/3343536/c022ce0c-533a-4985-b533-24f20e4acc76">

**Comment by ericboucher** [comment]
@wadhwamatic I think this is because they have the same FloodNumber. So we only keep the latest data.
I tried changing the floodN and it was aggregating properly then.

**Comment by wadhwamatic** [comment]
@ericboucher - Thanks for clarifying this. I made two submissions for the same flood number but the stats that show up in the report are for the earlier submission. Shouldn't it use the last submission for a given flood number?

This is the first form submission:
https://staging-dmp.ovio.org/form/FLOOD/427963098

And this is the second:
https://staging-dmp.ovio.org/form/FLOOD/427963464

The report shows data from the first submission:
<img width="1580" alt="Screenshot 2023-05-18 at 14 19 52" src="https://github.com/WFP-VAM/dmp/assets/3343536/e028c4be-d76b-4eac-9594-2942e7fa3a3d">

The above was all tested with one flood number. Once I added submissions using flood number 2, I see aggregation happening. But it's still aggregating on form 427963098 instead of 427963464

**Comment by ericboucher** [comment]
@wadhwamatic at the moment it is meant to get the data with the latest disasterDate. I guess it was not expected to have multiple reports with the same disaster date and same flood number that are all approved. No?

**Comment by wadhwamatic** [comment]
@ericboucher - yeah, it's probably an edge case that wouldn't happen often. But since we see this, can we also use the same approach as sorting, where we get latest date and secondarily get last update? I don't think I approved either of these forms BTW
