### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/dmp#97]
I believe there are more but here are a few translations which I noticed missing immediately

<img width="1400" alt="Screenshot 2023-05-11 at 19 22 05" src="https://github.com/WFP-VAM/dmp/assets/3343536/2e2dacf1-87e2-4876-9c73-25efe5e36981">

<img width="1402" alt="Screenshot 2023-05-11 at 19 22 14" src="https://github.com/WFP-VAM/dmp/assets/3343536/ed5b49f5-eed9-4d2b-9b5c-a3501488ea7d">

The `review` link is also missing a translation

**Comment by ericboucher** [comment]
@wadhwamatic I translated a few more bits in #107, it might be useful to have someone on the Cambodia team review the PR though.

For missing district / commune, do you know where we can find the data? This district is indeed missing from the translation files.

**Comment by ericboucher** [comment]
This is the translation file from the old ruby version for reference - [i18n.js.zip](https://github.com/WFP-VAM/dmp/files/11498474/i18n.js.zip)

**Comment by ericboucher** [comment]
https://docs.google.com/spreadsheets/d/1mHNVEN-zU5Y2_4qTsgUvIJaz4Fm3h2TNje71HdgLkcs/edit#gid=2021136198
